Ft send travel request
atlp-rwanda/phoenix-bn-backend pull request #19
Opened 2020-11-02 13:00 UTC by muhireheir

2020-11-04 14:04 UTC, bizip requested changes
Great job on this PR, but there is some test that is not passing at all. maybe your work is not updated to develop branch.

2020-11-04 15:19 UTC, Faustin250 approved these changes
Great job

2020-11-05 07:08 UTC, bizip approved these changes

2020-11-05 14:42 UTC, nkalyesubula approved these changes
LGTM

2020-11-05 14:42 UTC, merged