The user should be able to book an accomodation
atlp-rwanda/phoenix-bn-backend pull request #25
Opened 2020-11-20 18:48 UTC by Faustin250

### What does this PR do?
> This PR allow users to book an accommodation
### Description of Task to be completed
>-book an accommodation endpoint
>-check accommodation availability
>-view booked accommodation
 ### How should this be manually tested?
>-Clone the repos
>-Switch to the `ft-bookAccomodation` branch
>-Add the env variables in `.env` file
>-Your `.env` file should look like this : 
>     - `DB_PORT=`  
>     - `DB_HOST=`  
>     - `DB_USER=`
>     - `DB_PASSWORD=`
>     - `DB_NAME=`  
>     - `DB_DIALECT=`  
>     - `DATABASE_URL=`
>     - `JWTKEY=`
>     - `API_VERSION=v1`
>     - `EMAIL=nomadbarefoot2@gmail.com`
>     - `PASSWORD=nistnvpuhqalrrej`
>     - `CLIENT_ID=978352907060-j1m2j5j0upfajnh6ln5idcnr9f4fk551.apps.googleusercontent.com`
>     - `CLIENT_SECRET=-ABEMIKgnYnvC3RIrhTQLO-F`
>     - `APP_SECRET=5efb78c04b84aead6f3b4587a76d8e2f`
>     - `APP_ID=631208460883265`
>     - `JWT_SECRET_KEY=`
>     - `appPassword=nistnvpuhqalrrej`
>     -`CLOUD_NAME=faustin250`
>     -`CLOUD_API_KEY=886115265422219`
>     -`CLOUD_API_SECRET=3tYIbq4FrNHFj6ix2BWqwc_uvhY`
>     - `HOST=http://localhost:5000`
>     - `PORT=5000`
> run `npm install` to install the required package dependances
> run `npm run db:migrate:undo:all` to undo all migrations
> run `npm start` to run the application
 
### Any background context you want to provide?
>  The user will be able to see the availability of the accommodations and be able to book the room
### What are the relevant Trello story?
> Ft-bookAccomodation >> https://trello.com/c/nxtAgYUw/16-book-an-accommodation
### Screenshots 
>> login as requester (requester@barefoot.com,pswd:123456)

![1](https://user-images.githubusercontent.com/49835290/98448995-c318ce00-2138-11eb-98f4-e5818e388f1e.PNG)

>Pass auth key into the header and proceed with the following

![1](https://user-images.githubusercontent.com/49835290/99838224-7211cc80-2b71-11eb-8348-4b5eaaecb49a.PNG)

>Pass auth key into the header and proceed with the following

![2](https://user-images.githubusercontent.com/49835290/99838283-8e156e00-2b71-11eb-865c-3790c1fc7ce8.PNG)

>Pass auth key into the header and proceed with the following

![3](https://user-images.githubusercontent.com/49835290/99838331-a2f20180-2b71-11eb-86a7-c76137f9c325.PNG)

2020-11-20 18:50 UTC, Faustin250 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Book an accommodation](https://trello.com/c/nxtAgYUw/16-book-an-accommodation)

2020-11-21 10:55 UTC, nkalyesubula requested changes
Good work sofar. I have left some change requests though. In addition, please write tests and come up with a swagger doc

2020-11-21 10:55 UTC, nkalyesubula commented on src/migrations/20201103084825-create-accomodations.js
> +      roomCapacity: {
Just use "capacity"

2020-11-21 10:55 UTC, nkalyesubula commented on src/migrations/20201103084825-create-accomodations.js
> +      roomLeft: {
use "roomsLeft"

2020-11-21 10:55 UTC, nkalyesubula commented on src/controllers/bookController.js
> +                checkOut: req.body.checkOut
a status property is missing....It should have a value of  "active" by default

2020-11-21 10:55 UTC, nkalyesubula commented on src/migrations/20201108154514-create-rooms.js
> +        defaultValue: "inactive",
it should be active by default...if a user is checked out, it will be updated to inactive

2020-11-21 10:55 UTC, nkalyesubula commented on src/models/accomodations.js
> +    roomLeft: DataTypes.INTEGER,
Change these to "capacity" and "roomsLeft" respectively

2020-11-23 07:53 UTC, nkalyesubula approved these changes
LGTM

2020-11-23 07:53 UTC, merged