fixing problems that was causing production app on heroku to crash
atlp-rwanda/phoenix-bn-backend pull request #9
Opened 2020-10-16 10:41 UTC by muhireheir

2020-10-16 14:18 UTC, mugisha1555 approved these changes

2020-10-16 14:28 UTC, Faustin250 approved these changes

2020-10-16 15:39 UTC, nellyganza approved these changes
It's nice

2020-10-17 08:12 UTC, nkalyesubula requested changes
Looks good so far. Lets improve on the PR title. "Fix errors on Heroku staging app" would be a better PR title

2020-10-17 08:48 UTC, nkalyesubula approved these changes

2020-10-17 08:48 UTC, merged